import Foundation
import SwiftData

/// Represents a planned workout generated by the AI coach.
@Model
final class WorkoutPlan {
    var id: UUID
    var createdAt: Date
    var scheduledDate: Date
    var completed: Bool
    var completedDate: Date?

    // Workout details
    var title: String
    var workoutDescription: String
    var workoutType: String            // "steady_state", "interval", "test", "recovery", "cross_training"
    var targetDistanceMeters: Int?
    var targetTimeSeconds: Double?
    var targetSplit: Double?           // target /500m split
    var targetStrokeRate: Int?
    var targetHeartRateZone: Int?      // 1-5

    // Interval details
    var intervals: [IntervalBlock]?

    // AI reasoning
    var aiReasoning: String            // Why the AI prescribed this workout
    var difficultyRating: Int          // 1-10
    var focusArea: String              // "aerobic_base", "threshold", "power", "technique", "recovery"

    // Linked score after completion
    var linkedScoreId: UUID?

    init(
        title: String,
        workoutDescription: String,
        workoutType: String,
        aiReasoning: String,
        difficultyRating: Int = 5,
        focusArea: String = "aerobic_base"
    ) {
        self.id = UUID()
        self.createdAt = Date()
        self.scheduledDate = Date()
        self.completed = false
        self.title = title
        self.workoutDescription = workoutDescription
        self.workoutType = workoutType
        self.aiReasoning = aiReasoning
        self.difficultyRating = difficultyRating
        self.focusArea = focusArea
    }

    var formattedTargetSplit: String? {
        guard let split = targetSplit else { return nil }
        let minutes = Int(split) / 60
        let seconds = split - Double(minutes * 60)
        return String(format: "%d:%04.1f", minutes, seconds)
    }
}

/// A block within an interval workout.
struct IntervalBlock: Codable, Hashable {
    var reps: Int
    var distanceMeters: Int?
    var timeSeconds: Double?
    var targetSplit: Double?
    var targetStrokeRate: Int?
    var restSeconds: Double

    var description: String {
        let work: String
        if let dist = distanceMeters {
            work = "\(dist)m"
        } else if let time = timeSeconds {
            let min = Int(time) / 60
            let sec = Int(time) % 60
            work = "\(min):\(String(format: "%02d", sec))"
        } else {
            work = "?"
        }

        let restMin = Int(restSeconds) / 60
        let restSec = Int(restSeconds) % 60
        let rest = restMin > 0 ? "\(restMin):\(String(format: "%02d", restSec))" : "\(restSec)s"

        return "\(reps)x\(work) / \(rest)r"
    }
}

/// Represents training week summary for trend tracking.
@Model
final class WeekSummary {
    var id: UUID
    var weekStartDate: Date
    var totalMeters: Int
    var totalSessions: Int
    var totalTimeSeconds: Double
    var averageSplit: Double?
    var averageHR: Int?
    var hardSessionCount: Int
    var easySessionCount: Int
    var trainingLoad: Double          // TSS-like metric

    init(weekStartDate: Date) {
        self.id = UUID()
        self.weekStartDate = weekStartDate
        self.totalMeters = 0
        self.totalSessions = 0
        self.totalTimeSeconds = 0
        self.hardSessionCount = 0
        self.easySessionCount = 0
        self.trainingLoad = 0
    }
}
